services:
  hadoop:
    build:
      context: ..
      dockerfile: cluster/Dockerfile
    container_name: qaliwarma-hadoop
    ports:
      - "50070:50070"   # NameNode UI
      - "8088:8088"     # ResourceManager UI (monitor de recursos)
      - "9000:9000"     # HDFS RPC
    volumes:
      - hadoop_data:/hadoop-data
    stdin_open: true
    tty: true

volumes:
  hadoop_data:
